#!/usr/bin/env bash
set -euo pipefail

DB_NAME="${MYSQL_DATABASE:-famtastic_by_the_numbers}"
DB_USER="${MYSQL_USER:-btn_local}"
DB_PASSWORD="${MYSQL_PASSWORD:-btn_local_pass}"
DB_HOST="${MYSQL_HOST:-127.0.0.1}"
ROOT_USER="${MYSQL_ROOT_USER:-root}"
ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-}"
MYSQL_BIN="${MYSQL_BIN:-mysql}"

if [[ -n "$ROOT_PASSWORD" ]]; then
  "$MYSQL_BIN" -u "$ROOT_USER" -h "$DB_HOST" -p"$ROOT_PASSWORD" <<SQL
CREATE DATABASE IF NOT EXISTS \
  \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';
CREATE USER IF NOT EXISTS '$DB_USER'@'127.0.0.1' IDENTIFIED BY '$DB_PASSWORD';
GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost';
GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL
else
  "$MYSQL_BIN" -u "$ROOT_USER" -h "$DB_HOST" <<SQL
CREATE DATABASE IF NOT EXISTS \
  \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';
CREATE USER IF NOT EXISTS '$DB_USER'@'127.0.0.1' IDENTIFIED BY '$DB_PASSWORD';
GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost';
GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL
fi

echo "Bootstrapped MySQL database '$DB_NAME' with user '$DB_USER'."