"""Deliverable generators — the actual product of the worker agents.

Each function returns finished Markdown. In OFFLINE mode these generators ARE
the model output (deterministic, reviewable, and genuinely useful). In LIVE
mode the same prompts would be sent to the routed model; the accounting is
identical either way (see router.call_model).

The proof job: build the COMPLETE go-to-market + sell + collect pipeline for
selling FAMtastic Designs as a productized service, for internal use. These are
solutions, not suggestions — every artifact is ready to copy, send, or run.
"""
from __future__ import annotations

import datetime as _dt

from factory_paths import load_env

TODAY = _dt.date.today().isoformat()


def _ctx() -> dict:
    env = load_env()
    return {
        "paypal": env.get("PAYPAL_BUSINESS_EMAIL") or "[your-paypal-business-email]",
        "domain": env.get("GODADDY_DOMAIN") or "[yourdomain.com]",
        "outreach_email": env.get("GODADDY_OUTREACH_EMAIL") or "fritz@[yourdomain.com]",
    }


def _header(title: str, subtitle: str) -> str:
    return (
        f"# {title}\n\n"
        f"> {subtitle}\n>\n"
        f"> Generated by the Agent Factory · {TODAY} · internal use only\n\n"
    )


# --------------------------------------------------------------------------- #
# 1. Business model
# --------------------------------------------------------------------------- #
def business_model(payload: dict) -> str:
    c = _ctx()
    return _header(
        "FAMtastic Designs — Business Model & Offer Architecture",
        "Productizing the FAMtastic site factory into a repeatable revenue engine.",
    ) + f"""
## The one-line model
We sell *confidently-different* websites — produced by the FAMtastic factory in
days, not months — through a value ladder that lands a small paid win first,
then upgrades it into a full build and a recurring care plan.

## Why this wins
- **Production cost is near-zero and falling.** The factory already builds
  multi-page, motion-rich sites from a brief. Our marginal cost per site is
  hours of review, not weeks of design labor. That is the arbitrage.
- **We lead with a paid diagnostic, not a free pitch.** A small paid first step
  qualifies the buyer, funds outreach, and creates the artifact that closes the
  bigger sale.
- **Every delivery produces a reusable asset** (before/after, Loom, template),
  which compounds into proof for the next sale.

## The value ladder (offer architecture)
| Rung | Offer | Price | Purpose | Turnaround |
|------|-------|-------|---------|-----------|
| 0 — Tripwire | **Conversion Leak Audit** | $149 | Cheap yes, fills pipeline | 48h |
| 1 — Entry | **Checkout / Funnel Rescue Diagnostic** | $500 flat | Qualifies serious buyers, credits toward build | 48h |
| 2 — Core | **FAMtastic Site Build** (3 tiers below) | $1,500 / $3,500 / $7,500 | The money | 5–10 days |
| 3 — Recurring | **Care + Hosting Plan** (GoDaddy reseller bundle) | $79–$199 / mo | Predictable MRR | ongoing |
| 4 — Expansion | **Growth Retainer** (CRO, pages, campaigns) | $1,500+/mo | LTV | ongoing |

### Core build tiers
- **Launch ($1,500):** 3-page FAMtastic site, 1 hero vocabulary, contact form,
  basic SEO, deploy. The factory's default output, reviewed and shipped.
- **Signature ($3,500):** 5–7 pages, custom hero + character branding, motion,
  copywriting pass, analytics + lead capture wired, 1 revision round.
- **Flagship ($7,500):** Everything in Signature + booking/payment integration,
  multi-vertical content, A/B-ready hero variants, 30-day post-launch tuning.

## Unit economics (per Signature build, conservative)
- Price: **$3,500**
- Factory + review cost (compute + ~4h human review @ blended $50/h): ~**$250**
- Outreach cost to land it (CAC at 2% reply→close on paid outreach): ~**$300**
- **Contribution margin: ~$2,950 (84%)** before the recurring plan.
- Add care plan at $129/mo → **~$1,548 ARR** per client on top.

## The "diagnostic funds the machine" loop
1. Sell a $500 diagnostic. 2. Deliver in 48h with a Loom. 3. Credit the $500
toward a build if they hire within 7 days. 4. The build funds the next 10
outreach batches. 5. The care plan turns one-time cash into MRR. This is the
flywheel — paid at every step so the pipeline never runs on hope.

## Revenue targets (first 90 days, deliberately modest)
- Month 1: 4 diagnostics ($2,000) + 1 build ($3,500) = **$5,500**
- Month 2: 6 diagnostics + 2 builds + 3 care plans = **~$11,400**
- Month 3: convert backlog → 4 builds + 8 care plans = **~$18,000 + $1,032 MRR**

## Assumptions logged
- PayPal Business is the payment rail (`{c['paypal']}`); invoicing flow in the
  payment deliverable.
- Custom sending domain + email via GoDaddy (`{c['domain']}`); deliverability
  steps in the outreach deliverable.
- No paid ads until the first paid job proves the lane (organic + direct
  outreach first). Ads section is built but gated behind first revenue.
"""


# --------------------------------------------------------------------------- #
# 2. Marketing strategy
# --------------------------------------------------------------------------- #
def marketing_strategy(payload: dict) -> str:
    return _header(
        "FAMtastic Designs — Marketing & Positioning",
        "How we say it, to whom, and why they believe it.",
    ) + """
## Positioning statement
For small businesses and agencies with a website that looks generic or leaks
revenue, **FAMtastic Designs** builds *confidently-different* sites in days —
proof-driven craft that a normal agency would not ship — without the months-long
agency timeline or the cookie-cutter template look.

## Who we target first (beachhead, in priority order)
1. **Agencies with overflow** — they have demand they can't service; we are the
   white-label factory behind them. Fastest cash, repeat buyers.
2. **Merchants with a live, leaking checkout/funnel** — acute pain, paid
   diagnostic lands easily.
3. **Local service businesses with an embarrassing site** — barber, bakery,
   transport, flowers (the factory already has proof builds in these verticals).

## Message hierarchy
- **Hook (pain):** "A generic site is quietly costing you customers."
- **Proof (craft):** before/after artifacts, Loom walkthroughs, 48h turnaround.
- **Offer (low-risk first step):** the $149 audit / $500 diagnostic.
- **Close (results are the proof):** "If the fixes don't make sense, you keep
  the audit and owe nothing further."

## Proof assets to manufacture (from real deliveries)
- One public-safe **before/after** per completed build.
- A 3–5 min **Loom** narrating the leak found and the fix.
- A one-page **case snapshot** (problem → change → measurable result).
- A reusable **hero gallery** screenshot reel from factory builds.

## Channels (ranked by speed-to-cash, not by reach)
1. **Direct outreach** (email + LinkedIn) — controllable, fast, free.
2. **Upwork / marketplaces** — buyers with budget and intent already there.
3. **Referral loop** — every delivered job asks for one intro.
4. **Content proof** — post each before/after; let the work recruit.
5. **Paid (gated):** small LinkedIn/Google spend behind a "conversion leak
   audit" page — only after the first paid job exists. Retargeting only after
   traffic exists.

## Brand voice
FAMtastic: fearless, specific, unapologetic, proof-over-promises. No hedging, no
"we think we can help." We diagnose, we fix, the result is the argument.

## 30-day marketing calendar (lightweight)
- Wk1: publish offer page + 2 proof artifacts; start outreach.
- Wk2: 3 posts (before/after, the "leak" idea, a client win); referral asks.
- Wk3: turn best-performing message into the outreach default; first case study.
- Wk4: gate-check — if ≥1 paid job, switch on a $10–20/day audit-page test.
"""


# --------------------------------------------------------------------------- #
# 3. Campaign plan
# --------------------------------------------------------------------------- #
def campaign_plan(payload: dict) -> str:
    return _header(
        "FAMtastic Designs — Campaign Plan",
        "The concrete first campaign: lanes, cadence, budget, and stop/go gates.",
    ) + """
## Primary lane (run this first, exclusively)
**"Conversion Leak / Checkout Rescue" diagnostic campaign.** One offer, one
message, two outreach channels, one paid entry point. Do not split focus until
this lane produces cash.

## Backup lane (activate only if primary stays dead 48h)
**"Google Ads / Tracking Leak Audit" — $149.** Same machine, different pain.
Kept on the shelf, not run in parallel — parallel lanes dilute the test.

## Campaign structure
- **Audience A — Agencies:** offer = white-label overflow builds + rescue.
- **Audience B — Merchants:** offer = $500 checkout/funnel rescue diagnostic.
- **Audience C — Local services:** offer = $149 audit → Launch build.

## Cadence (per business day, first 2 weeks)
- 10 tailored Upwork/marketplace proposals before noon.
- 10 direct emails + 10 LinkedIn DMs from the 25-target daily list.
- 100% of replies answered within 2 working hours.
- 1 proof artifact published every 2 days.

## Budget plan
- **Weeks 1–2: $0 paid.** Pure outreach. Cost is time, not cash.
- **Gate 1 (after first paid job):** turn on $10–20/day to a single audit
  landing page. Kill any ad set under a 2% landing-conversion after $100 spend.
- **Gate 2 (after 3 paid jobs):** add retargeting only once real traffic exists.
- **Hard rule:** ad spend never exceeds 20% of trailing-30-day collected revenue.

## Stop / go gates
| Gate | Condition | Action |
|------|-----------|--------|
| G0 | 0 replies in 48h on primary lane | activate backup lane in parallel |
| G1 | 1 paid diagnostic closed | switch on small paid test, build case study |
| G2 | 3 paid jobs collected | add retargeting + raise build prices 10% |
| G3 | CAC > 25% of order value for 7 days | pause paid, return to pure outreach |

## First-10 execution actions (today)
1. Lock the offer copy (one sentence) — done in the sales deliverable.
2. Publish the one-page sales doc (scope, price, CTA, turnaround).
3. Finalize the 6-point diagnostic checklist.
4. Two proposal templates ready: merchant-direct + agency-overflow.
5. Stand up the reusable Upwork/marketplace proposal block.
6. Shortlist 20 relevant jobs (Authorize.Net, checkout fix, WooCommerce
   payment, payment-gateway cleanup, "site redesign").
7. Send 10 tailored proposals before noon.
8. Build the 25-target outreach list (agencies + merchants).
9. Send 10 direct emails + 10 DMs offering the diagnostic.
10. Prep the Loom template so delivery starts the same day someone bites.
"""


# --------------------------------------------------------------------------- #
# 4. Outreach / contacting system
# --------------------------------------------------------------------------- #
def outreach_system(payload: dict) -> str:
    c = _ctx()
    return _header(
        "FAMtastic Designs — Outreach & Contacting System",
        "Lists, sequences, copy, and deliverability — ready to send.",
    ) + f"""
## Sending setup (GoDaddy)
- Sending identity: **{c['outreach_email']}** on **{c['domain']}**.
- Deliverability checklist (do before sending volume):
  1. Add **SPF** record: `v=spf1 include:secureserver.net ~all` (GoDaddy email)
     or your ESP's include if you route through one.
  2. Enable **DKIM** in the GoDaddy/email-provider console; publish the CNAMEs.
  3. Add a **DMARC** record: `v=DMARC1; p=none; rua=mailto:dmarc@{c['domain']}`.
  4. **Warm up:** ≤20 sends/day week 1, ≤40 week 2; reply to every response.
  5. Plain text, no images, one link max, real signature. No "Dear Sir/Madam".

## Target list build (25/day)
- Sources: Upwork job posters, agency directories (Clutch/Sortlist), local
  business listings with weak sites, Shopify/WooCommerce stores with broken
  checkout (test the cart yourself — that's your opening line).
- Capture per target: name, business, site URL, the *specific* flaw you saw,
  channel (email/LinkedIn), status.
- Disqualify: no website, no budget signal, dead business.

## Sequence A — Merchant direct (checkout/funnel rescue, $500)
**Email 1 (Day 0) — the specific observation**
> Subject: noticed something on {{business}}'s checkout
>
> Hi {{first_name}} — I went through {{business}}'s checkout to buy and hit
> {{specific_flaw}}. That's the kind of thing that quietly kills completed
> orders. I run a 48-hour Checkout Rescue Diagnostic ($500 flat): I map the
> flow, find what's leaking, and hand you a prioritized fix plan + a short Loom
> walking you through it. If the findings aren't worth the $500, I'll tell you
> that on the call. Want me to take a look this week?
> — Fritz, {c['outreach_email']}

**Email 2 (Day 3) — proof nudge**
> Subject: re: {{business}}'s checkout
> Quick follow-up — here's a 90-sec sample of what the diagnostic looks like
> [Loom link]. Same thing, on your store, in 48 hours. Worth a look?

**Email 3 (Day 7) — break-up**
> Subject: closing the loop
> I'll stop here so I'm not a pest. If completed-checkout rate ever becomes a
> priority, the rescue diagnostic stands. Either way, good luck with {{business}}.

## Sequence B — Agency overflow (white-label builds)
**DM/Email 1**
> Subject: overflow capacity for {{agency}}?
> Hi {{first_name}} — I run a build studio that ships confidently-different,
> multi-page sites in days (white-label, your brand on it). If you ever have
> overflow or a client who needs a fast, distinctive build, I can be the engine
> behind it. Happy to do one fixed-scope build at $1,500 so you can pressure-test
> the quality with zero risk. Open to a quick look at a sample?

**DM 2 (Day 4)**
> Following up with a 2-min reel of recent builds [link]. If you've got a stuck
> project, I can turn it around this week.

## LinkedIn DM (short-form, Audience A/B)
> Hi {{first_name}} — saw {{business}}. I fix leaking checkouts / build fast,
> distinctive sites. I do a flat $500 48-hour diagnostic — want the 90-sec
> sample of what you'd get?

## Reply playbook
- "How much?" → restate flat price + turnaround + the credit-toward-build offer.
- "Send more info" → the one-page sales doc + Loom sample, then propose a time.
- "Not now" → ask permission to follow up in 30 days; tag in CRM.
- "Interested" → send PayPal invoice (payment deliverable) + intake form;
  delivery clock starts on payment.

## Tracking
- One row per target in the simple CRM (a CSV or the queue's payload is fine for
  v1): status = new → contacted → replied → invoiced → paid → delivered.
- Daily scoreboard: sent, replies, calls, invoices, collected.
"""


# --------------------------------------------------------------------------- #
# 5. Sales process
# --------------------------------------------------------------------------- #
def sales_process(payload: dict) -> str:
    return _header(
        "FAMtastic Designs — Sales Process, Offer Copy & Proposals",
        "From reply to signed-and-paid, with the exact words.",
    ) + """
## The offer, in one sentence
**"Broken checkout is lost revenue. I diagnose and stabilize your payment /
conversion flow in 48 hours — flat $500, credited toward the fix if you hire
me."**

## One-page sales doc (publishable)
**Checkout / Conversion Rescue Diagnostic — $500 flat, 48 hours**
- **Who it's for:** merchants or agencies with a live checkout/funnel that's
  leaking completed orders.
- **What you get:**
  1. Full checkout-flow audit (every step, every drop-off).
  2. Gateway / plugin / integration review (Authorize.Net, Stripe, WooCommerce,
     Shopify — wherever the money flows).
  3. Fraud / risk-rule check (false declines kill revenue too).
  4. Tokenization / recurring-billing check where relevant.
  5. A prioritized fix plan (what to fix first, expected impact).
  6. A Loom walkthrough so your team can act without a meeting.
- **Turnaround:** 48 hours from payment + access.
- **CTA:** "Send me your store URL and I'll start today."
- **Guarantee:** if the findings aren't worth the $500, I'll say so — you keep
  the full report regardless.

## Pricing sheet
| Item | Price | Notes |
|------|-------|-------|
| Conversion Leak Audit | $149 | 48h, Loom + fix sheet (tripwire) |
| Checkout Rescue Diagnostic | $500 flat | credited toward sprint |
| Implementation Sprint | $2,500–$4,000 | fixes the diagnosed issues |
| FAMtastic Launch build | $1,500 | 3-page factory site |
| FAMtastic Signature build | $3,500 | 5–7 pages, custom hero |
| FAMtastic Flagship build | $7,500 | + booking/payment, tuning |
| Care + Hosting plan | $79–$199/mo | recurring |

## Upsell mechanics
- The $500 diagnostic **credits in full** toward an implementation sprint if they
  hire within 7 days. This makes "yes" to the diagnostic nearly free in their
  head and pre-frames the bigger sale.
- After any build, offer the care plan as the default ("keep it fast, secure,
  and updated for $129/mo") — opt-out, not opt-in.

## Proposal template — Merchant direct
> **Checkout Rescue Diagnostic for {{business}}**
> The problem I saw: {{specific_flaw}}. Left alone, that's completed orders you
> paid to acquire and then lost at the last step.
> **Scope:** full flow audit, gateway/plugin review, fraud-rule check,
> tokenization/recurring check, prioritized fix plan, Loom walkthrough.
> **Price:** $500 flat. **Turnaround:** 48 hours from payment + access.
> **Next step:** approve and I'll send a PayPal invoice; the clock starts when
> it's paid and I have store access. The $500 credits toward the fix if you want
> me to implement.

## Proposal template — Agency overflow
> **White-label build capacity for {{agency}}**
> You bring the client and the brand; I'm the build engine behind it. Fixed
> scope, fast turnaround, your name on the result.
> **Pilot:** one Launch build at $1,500 so you can judge the quality risk-free.
> **Then:** Signature/Flagship at agency rates, or a per-build wholesale sheet.
> **Next step:** send me the brief; I'll return a sample direction in 48 hours.

## Objection handling
- *"$500 is a lot for an audit."* → "It's credited toward the fix, and you keep
  the report either way. The leak is costing more than $500/month — that's the
  point."
- *"We'll just look ourselves."* → "You can — the diagnostic is the 48-hour,
  prioritized version your team would take two weeks to produce, with a fix plan
  attached."
- *"Can you guarantee more sales?"* → "I guarantee a complete diagnosis and a
  prioritized plan. The fixes move the number; I'll show you the expected
  impact, ranked."

## Definition of a closed sale
Verbal/email "yes" → PayPal invoice sent → **invoice paid** → access received →
delivery clock starts. "Paid" is the only status that counts.
"""


# --------------------------------------------------------------------------- #
# 6. Payment & fulfillment
# --------------------------------------------------------------------------- #
def payment_fulfillment(payload: dict) -> str:
    c = _ctx()
    return _header(
        "FAMtastic Designs — Payment Collection & Fulfillment",
        "How cash actually lands and how the work ships — PayPal + GoDaddy.",
    ) + f"""
## Payment rail: PayPal Business
- Receiving account: **{c['paypal']}** (PayPal Business).
- **Primary method — PayPal Invoices** (no code, works today):
  1. PayPal Business → **Invoicing → Create Invoice**.
  2. Bill-to: client email. Line item: "Checkout Rescue Diagnostic — 48h" $500.
  3. Terms: **Due on receipt.** Enable partial-payment OFF. Turn ON the reminder.
  4. Send. Delivery clock starts when status flips to **Paid**.
- **Optional later — PayPal Checkout link / button** for the productized audit
  ($149) so the tripwire is self-serve. Use a **Payment Link** from the PayPal
  dashboard; drop it on the offer page. (Live API keys go in `.env`:
  `PAYPAL_CLIENT_ID`, `PAYPAL_CLIENT_SECRET` — see SETUP.md. The factory never
  calls these; they're for your storefront.)
- **Deposit policy for builds:** 50% to start, 50% on approval. Two invoices,
  same flow. Never start a build before the deposit clears.

## Invoice → cash state machine
`draft → sent → paid → delivered → (care-plan: subscribed)`
- `sent` but unpaid 48h → automatic PayPal reminder + one personal nudge.
- `paid` → send intake form, request access, start the 48h clock.
- `delivered` → send the care-plan opt-out offer + ask for one referral.

## Subscriptions (care plan MRR)
- Use **PayPal Subscriptions** (create a recurring plan in the dashboard) at
  $79/$129/$199/mo. Self-serve link on the post-delivery email.
- Dunning: PayPal retries failed charges automatically; on hard fail, pause the
  care service and email the client.

## Fulfillment pipeline (diagnostic, 48h)
1. **Intake (0–2h):** store URL, admin/staging access, payment processor in use,
   the specific symptom. Standard intake form below.
2. **Audit (2–24h):** walk the full checkout; log every step + drop-off; review
   gateway/plugin config, fraud rules, tokenization/recurring.
3. **Synthesize (24–36h):** prioritized fix plan (impact × effort), the report.
4. **Loom (36–44h):** 3–5 min narrated walkthrough of leak → fix.
5. **Deliver (44–48h):** report PDF + Loom + fix plan; offer the sprint with the
   $500 credit; ask for the referral.

## Fulfillment pipeline (FAMtastic build)
1. Deposit paid → brief intake (brand, pages, vertical, references).
2. **Factory build** via the FAMtastic site studio (the existing pipeline).
3. Human review pass (hero vocabulary, nav skeleton, logo wiring, no inline
   styles — the factory's own non-negotiables).
4. Staging link to client → 1 revision round (Signature+).
5. Final invoice (50%) → on payment, deploy to their domain.
6. Offer care plan → subscribe → recurring revenue.

## Standard intake form (paste into email or a form on {c['domain']})
- Business name + URL:
- What are you selling / who buys:
- Payment processor (Authorize.Net / Stripe / PayPal / other):
- Platform (Shopify / WooCommerce / custom):
- The symptom you've noticed:
- Admin or staging access (or a screen-share time):
- Anything off-limits to change:

## Receipts, taxes, records
- PayPal generates the receipt automatically; keep the PDF.
- Log each sale in the simple CRM/ledger (date, client, offer, amount, fees).
- Set aside ~25–30% of collected revenue for taxes (consult an accountant;
  this is an operational reminder, not advice).

## Hard money-safety rules (enforced by the sandbox too)
- The agent factory **never** charges anyone, moves money, or calls a payment
  API. It only *produces these documents and templates*. All real charges happen
  by you, in the PayPal dashboard, with your own credentials. (See SANDBOX.md.)
"""


# --------------------------------------------------------------------------- #
# Fallback generator for generic / triage tasks
# --------------------------------------------------------------------------- #
def generic(payload: dict, title: str = "Task") -> str:
    return _header(
        f"Worker Output — {title}",
        "Generic task processed by a factory worker.",
    ) + f"""
## Input
```json
{payload}
```

## Result
Processed successfully by the agent factory. This is a generic worker handler
used for tasks that do not map to a specialized deliverable generator. In LIVE
mode the routed model would produce the substantive output here from the task
payload; offline, this stub confirms the end-to-end claim → process → report →
cost-accounting path works.
"""


# Dispatch table: task type -> generator
GENERATORS = {
    "business_model": business_model,
    "marketing_strategy": marketing_strategy,
    "campaign_plan": campaign_plan,
    "outreach_system": outreach_system,
    "sales_process": sales_process,
    "payment_fulfillment": payment_fulfillment,
}


def generate(task_type: str, payload: dict, title: str = "Task") -> str:
    fn = GENERATORS.get(task_type)
    if fn is None:
        return generic(payload, title)
    return fn(payload)
