"""factory.py — mints concrete worker modules from worker_template.py.

The orchestrator calls mint_worker(kind) to get (or create) a runnable worker
module specialized for a task kind. Minted files land in workers/ and are
gitignored (they are regenerated on demand, not source).
"""
from __future__ import annotations

from pathlib import Path

import core

TEMPLATE = core.ROOT / "worker_template.py"

SPECIALTY = {
    "triage":    "fast classification & routing of inbound items",
    "classify":  "label/intent tagging of short inputs",
    "summarize": "condensing text into briefs",
    "research":  "multi-step investigation & recommendation",
    "codegen":   "writing and refactoring code",
}


def worker_path(kind: str) -> Path:
    return core.WORKERS_DIR / f"worker_{kind}.py"


def mint_worker(kind: str) -> Path:
    """Create (idempotently) a concrete worker module for `kind`.

    Returns the path to the runnable module. If it already exists it is reused —
    the factory does not re-mint identical agents needlessly.
    """
    core.ensure_dirs()
    dest = worker_path(kind)
    if dest.exists():
        return dest
    src = TEMPLATE.read_text(encoding="utf-8")
    minted = (
        src.replace("__WORKER_KIND__", kind)
           .replace("__WORKER_SPECIALTY__", SPECIALTY.get(kind, "general task work"))
           .replace("__MINTED_AT__", core.now_iso())
    )
    header = (
        f"# AUTO-GENERATED by factory.mint_worker('{kind}') at {core.now_iso()}.\n"
        f"# Do not edit by hand — regenerated on demand. Source: worker_template.py\n"
    )
    dest.write_text(header + minted, encoding="utf-8")
    return dest


def retire_minted(kind: str) -> bool:
    """Delete a minted worker module (cleanup). The template is never touched."""
    dest = worker_path(kind)
    if dest.exists():
        dest.unlink()
        return True
    return False


def list_minted() -> list[str]:
    return sorted(p.name for p in core.WORKERS_DIR.glob("worker_*.py"))
