'use strict';

/*
 * memo-agent — writes a daily digest into the collective brain.
 *
 * Pulls the same KPIs the monitor computes (no side effects) plus today's audit
 * events, and writes obsidian/Agent-Business-OS/digests/<date>.md. This is the
 * "record proof / post-evaluation" trail in human-readable form. Override the
 * output dir with ABOS_DIGEST_DIR (tests point it at a temp dir).
 */

const fs = require('fs');
const path = require('path');
const store = require('./lib/store');
const monitor = require('./monitor-agent');

function digestDir() {
  return process.env.ABOS_DIGEST_DIR ||
    path.join(__dirname, '..', '..', 'obsidian', 'Agent-Business-OS', 'digests');
}

function run() {
  const db = store.load();
  const health = monitor.compute(db);
  const k = health.kpis;
  const today = new Date().toISOString().slice(0, 10);

  const todays = store.readEvents().filter((e) => e.at && e.at.slice(0, 10) === today);
  const counts = todays.reduce((m, e) => { m[e.type] = (m[e.type] || 0) + 1; return m; }, {});

  const lines = [
    `# Agent Business OS — Daily Digest ${today}`,
    '',
    `> Auto-generated by \`memo-agent\`. Status: **${health.status.toUpperCase()}**`,
    '',
    '## KPIs',
    '',
    `- **Cash today:** $${k.cashToday}` + (k.cashTarget ? ` (target $${k.cashTarget})` : ''),
    `- **Cash trailing 7d:** $${k.cashTrailing7}`,
    `- **Open pipeline:** $${k.openPipeline}`,
    `- **Leads:** ${k.leads} · **Deals:** ${k.deals} · **Invoices:** ${k.invoices}`,
    `- **Deals by status:** ${fmtMap(k.dealsByStatus)}`,
    `- **Invoices by status:** ${fmtMap(k.invoicesByStatus)}`,
    '',
    '## Alerts',
    '',
    `- SLA breaches: ${health.alerts.slaBreaches}`,
    `- Overdue invoices: ${health.alerts.overdueInvoices}`,
    `- Escalated invoices: ${health.alerts.escalatedInvoices}`,
    '',
    '## Activity today',
    '',
    Object.keys(counts).length
      ? Object.entries(counts).map(([t, n]) => `- ${t}: ${n}`).join('\n')
      : '- (no agent activity logged today)',
    ''
  ];

  const dir = digestDir();
  fs.mkdirSync(dir, { recursive: true });
  const out = path.join(dir, `${today}.md`);
  fs.writeFileSync(out, lines.join('\n'));
  store.logEvent('memo-agent', 'digest_written', out, { status: health.status });
  return out;
}

function fmtMap(m) {
  const keys = Object.keys(m || {});
  return keys.length ? keys.map((s) => `${s}=${m[s]}`).join(', ') : 'none';
}

module.exports = { run };

if (require.main === module) {
  console.log('memo-agent: wrote', run());
}
