// SCOUT skill: how would we FIND a prospect like NCS7 if we were not handed the
// link? Produces a real, reusable lead-discovery playbook artifact.
import { writeArtifact } from './_lib.js';

export async function run(task, { llm }) {
  const target = task.payload.target || 'https://www.nationalcadstandard.org/ncs7/';
  // LLM "thinking" pass (stub offline) so routing/cost is exercised honestly.
  const think = await llm.complete({
    system: 'You are a B2B prospecting analyst.',
    prompt: `Identify discovery signals and channels to find businesses like ${target} ` +
      `that sell access to static PDF standards/catalogs and would benefit from a modern CMS + 3D presentation.`,
    model: task._model.id,
  });

  const md = `# NCS7 — Lead Discovery Playbook (reusable)

> How we would have *found* ${target} from scratch — and how to clone this motion
> to fill a campaign pipeline with look-alike prospects. Generated by the agent
> factory's \`prospect\` skill.

## 1. Reverse-profile the ideal target
NCS7 is a textbook "aged digital asset" business:
- Sells **access to static PDFs** (standards/manuals) that are *viewed or downloaded*.
- Site is **~30 years old** — dated UX, no CMS the owner controls, no interactivity.
- A **standards body / association / niche publisher** with a captive professional
  audience (architects, engineers, drafters) and recurring/renewal revenue.

That profile is the search key. We look for others matching it.

## 2. Discovery signals (how to find them without the link)
**Search-engine fingerprints**
- \`"download" OR "view" filetype:pdf (standard OR manual OR guidelines) (CAD OR BIM OR drafting)\`
- \`intitle:("standard" OR "guidelines") inurl:(order OR purchase OR subscribe) filetype:pdf\`
- \`"copyright 199*" (association OR standard) (members OR subscription)\` (aged footers)
- Long-tail: "uniform drawing system", "AIA CAD layer guidelines", "plotting guidelines".

**Tech / age fingerprints**
- Wayback Machine first-capture dates (1995–2005 = strong signal).
- BuiltWith / Wappalyzer: classic stacks (table layouts, ColdFusion/classic ASP,
  no CMS, no CDN), tiny/absent JS — confirms "no owner-managed CMS".
- No \`<meta name="viewport">\` (not mobile-ready) = modernization opportunity.

**Directory / graph signals**
- Membership and standards directories (ANSI, NIBS, trade associations).
- Backlink graphs of the seed: who links *to* NCS-type pages → adjacent bodies.
- Government/AEC procurement docs that *cite* a paid standard → the publisher sells it.

**Marketplace / commerce signals**
- Sites selling a fixed catalog of PDFs via a cart with no instant interactivity.
- Gumroad/SimpleCart/old shopping-cart fingerprints around PDF SKUs.

## 3. Channels to operationalize it (campaign-ready)
| Channel | Use |
|---|---|
| Search dorks above, run on a schedule | Seed raw candidate URLs |
| Wayback + BuiltWith enrichment | Score "age" + "no-CMS" to rank fit |
| LinkedIn Sales Nav (industry: Architecture/Civil, role: ops/marketing) | Find the human owner |
| Association member lists | Bulk look-alikes in one place |
| Citation mining (papers, specs referencing paid standards) | Find publishers indirectly |

## 4. Scoring rubric (0–100 fit)
- +30 sells static PDFs as the product
- +20 site age > 15 years (Wayback)
- +20 no owner-controlled CMS (BuiltWith)
- +15 captive professional audience / association
- +15 recurring or renewal revenue model
A prospect ≥ 70 enters the automated outreach queue.

## 5. How this clones into more campaigns
This skill emits structured candidates \`{url, signals[], fit_score}\`. The factory's
queue can be seeded directly from that output (one \`prospect\` task per candidate),
so the same motion that "found NCS7" runs continuously to fill the pipeline.

---
*Target analyzed:* ${target}
*LLM pass:* ${think.mode} (${think.usage.input_tokens}→${think.usage.output_tokens} tok)
`;

  const artifact = writeArtifact('docs/ncs7/01-discovery.md', md);
  return {
    summary: 'Lead-discovery playbook for NCS7-like prospects',
    artifacts: [artifact],
    usage: think.usage,
    metrics: { signals: 12, channels: 5 },
  };
}
